lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_task
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  def get_current_task(conn, _params) do
    # TODO: Move this function out of the router module.
    task_id = get_session(conn, :task_id)
    IO.inspect("#{task_id}")
    task = Tasktracker.TaskTrack.get_task(task_id || -1)
    assign(conn, :current_task, task)
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/posts", PostController
    resources "/tasks", TaskController
    get "/tasks/report/new", TaskController, :report
    post "/session", SessionController, :create
    post "/taskid", TaskidController, :create
    delete "/session", SessionController, :delete
#    get "/timeblocks1/new/:task", TimeBlockController, :new
    get "/timeblocks1/new", TimeBlockController, :new
   get "/timeblocks/:task", TimeBlockController, :editblock
  # get "/timeblocks/new/:task", TimeBlockController, :new
    post "/timeblocks/create1", TimeBlockController, :create1
    get "/timeblocks/:id/edit", TimeBlockController, :edit
    put "/timeblocks/:id", TimeBlockController, :update1
    delete "/timeblocks/:id", TimeBlockController, :delete1
  end

  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/timeblocks", TimeBlockController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker/accounts/user.ex
defmodule Tasktracker.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.Accounts.User


  schema "users" do
    field :email, :string
    field :name, :string
    field :admin, :boolean
    field :manager, :string
    has_many :task, Tasktracker.TaskTrack.Task, on_delete: :nilify_all, foreign_key: :user_id
    has_many :task1, Tasktracker.TaskTrack.Task, on_delete: :nilify_all, foreign_key: :assigned
    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :name, :admin, :manager])
    |> validate_required([:email, :name, :admin])
    |> unique_constraint(:email)
  end
end

lib/tasktracker_web/controllers/user_controller.ex
defmodule TasktrackerWeb.UserController do
  use TasktrackerWeb, :controller

  alias Tasktracker.Accounts
  alias Tasktracker.Accounts.User

  def index(conn, _params) do
    current_user = conn.assigns[:current_user]
    users = Accounts.list_users()
  #  follows = Tasktracker.TaskTrack.follows_map_for(current_user.id)
  #  followee = Tasktracker.TaskTrack.followee_map_for(current_user.id)
  #  manager= Accounts.get_user_by_email(current_user.manager)
  #underlings= Tasktracker.accounts.get_underlings(current_user.email)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end


end

lib/tasktracker_web/views/user_view.ex
defmodule TasktrackerWeb.UserView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= if(@current_user && @current_user.admin && @current_user.id != @user.id) do
 render "form1.html", Map.put(assigns, :action, user_path(@conn, :update, @user))
 else
   render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user))
 end
   %>

<%= if( @current_user.id != @user.id) do %>
<span><%= link "Back", to: user_path(@conn, :index) %></span>
<% else %>
 <span><%= link "Back", to: task_path(@conn, :index) %></span>
 <% end %>

lib/tasktracker_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, type: "email", placeholder: "user@example.com" ,class: "form-control" %>
    <%= error_tag f, :email %>
  </div>


  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :admin, class: "control-label" %>
    <%= checkbox f, :admin, class: "checkbox" %>
    <%= error_tag f, :admin %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/user/form1.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= hidden_input f, :email, value: @user.email,  class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= hidden_input f, :name, value: @user.name,  class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :manager, class: "control-label" %>
    <%= select f, :manager, Enum.map(Tasktracker.Accounts.list_users, &{&1.email, &1.email}),  class: "form-control" %>
    <%= error_tag f, :manager %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/user/index.html.eex
<%= if @current_user do %>
<%= if @current_user.admin==true do %>
<h2>Listing Users</h2>
<br>
<span><%= link "New User", to: user_path(@conn, :new) %></span><br><br>
<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Manager</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name %></td>
      <td><%= if user.manager== nil do "ASSIGN MANAGER" else user.manager end %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<br><br>
<span><%= link "Back", to: task_path(@conn, :index) %></span>
<% else %>
<br><br><br>
<h1>You are Not Admin</h1>
<br><br>
<h1><%= link "Login", to: page_path(@conn, :index) %></h1>
<% end %>
<% else %>
<br><br><br>
<h1><%= link "Login First", to: page_path(@conn, :index) %></h1>
<% end %>

lib/tasktracker_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: page_path(@conn, :index) %></span>

lib/tasktracker_web/templates/user/show.html.eex
<h2>Show User</h2>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Manager:</strong>
  <%= if @user.manager== nil do "No Manager" else @user.manager end %>
  </li>

</ul>

<span><%= link "Edit", to: user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: user_path(@conn, :index) %></span>