lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_task
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  def get_current_task(conn, _params) do
    # TODO: Move this function out of the router module.
    task_id = get_session(conn, :task_id)
    IO.inspect("#{task_id}")
    task = Tasktracker.TaskTrack.get_task(task_id || -1)
    assign(conn, :current_task, task)
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/posts", PostController
    resources "/tasks", TaskController
    get "/tasks/report/new", TaskController, :report
    post "/session", SessionController, :create
    post "/taskid", TaskidController, :create
    delete "/session", SessionController, :delete
#    get "/timeblocks1/new/:task", TimeBlockController, :new
    get "/timeblocks1/new", TimeBlockController, :new
   get "/timeblocks/:task", TimeBlockController, :editblock
  # get "/timeblocks/new/:task", TimeBlockController, :new
    post "/timeblocks/create1", TimeBlockController, :create1
    get "/timeblocks/:id/edit", TimeBlockController, :edit
    put "/timeblocks/:id", TimeBlockController, :update1
    delete "/timeblocks/:id", TimeBlockController, :delete1
  end

  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/timeblocks", TimeBlockController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker/task_track/task.ex
defmodule Tasktracker.TaskTrack.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.TaskTrack.Task


  schema "tasks" do
    field :completed, :boolean, default: false
    field :description, :string
    field :title, :string

    belongs_to :user, Tasktracker.Accounts.User, foreign_key: :user_id
    belongs_to :user1, Tasktracker.Accounts.User, foreign_key: :assigned
    has_many :timeblock, Tasktracker.TaskTrack.TimeBlock, on_delete: :nilify_all, foreign_key: :task_id
    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:title, :description, :assigned, :completed, :user_id])
    |> validate_required([:title, :description, :assigned, :completed, :user_id])
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:assigned)
  end
end

lib/tasktracker_web/controllers/task_controller.ex
defmodule TasktrackerWeb.TaskController do
  use TasktrackerWeb, :controller

  alias Tasktracker.TaskTrack
  alias Tasktracker.TaskTrack.Task

  def index(conn, _params) do
    tasks = TaskTrack.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = TaskTrack.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def report(conn, _params) do
    tasks = TaskTrack.list_tasks()
    render(conn, "report.html")
  end

  def create(conn, %{"task" => task_params}) do
    case TaskTrack.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = TaskTrack.get_task!(id)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = TaskTrack.get_task!(id)
    changeset = TaskTrack.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = TaskTrack.get_task!(id)

    case TaskTrack.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = TaskTrack.get_task!(id)
    {:ok, _task} = TaskTrack.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end

end

lib/tasktracker_web/views/task_view.ex
defmodule TasktrackerWeb.TaskView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/task/edit.html.eex
<h2>Edit Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/tasktracker_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= hidden_input f, :user_id,value: @current_user.id,  class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= textarea f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :assigned, class: "control-label" %>
    <%= select f, :assigned, Enum.map(Tasktracker.Accounts.get_underlings(@current_user.email), &{&1.email, &1.id}),  class: "form-control" %>
    <%= error_tag f, :assigned %>
  </div>

  <div class="form-group">
    <%= label f, :completed, class: "control-label" %>
    <%= checkbox f, :completed, class: "checkbox" %>
    <%= error_tag f, :completed %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/task/index.html.eex
<%= if @current_user do %>
<h2>Listing Tasks</h2>
<script>
window.time_block_path = "<%= time_block_path(@conn, :index) %>";
</script>

<br>
<%= if(length(Tasktracker.Accounts.get_underlings(@current_user.email)) > 0) do %>
<span><%= button "New Task", method: "get", class: "btn btn-primary", to: task_path(@conn, :new) %></span>
<% end %>
<span><%= button "Task Report", method: "get", class: "btn btn-primary", to: "/tasks/report/new" %></span>
<%= if(@current_user.admin) do %>
<span><%= button "Assign Managers To Users", method: "get", class: "btn btn-primary", to: user_path(@conn, :index) %></span>
<% end %>
<span><%= button "Edit Account", method: "get", class: "btn btn-primary", to: user_path(@conn, :edit, @current_user) %></span>
<br><br>
<table class="table">
  <colgroup>
    <col class="w">
    <col class="w">
    <col class="w2">
    <col class="w">
    <col class="w">
  </colgroup>
  <thead>
    <tr>
      <th>-</th>
      <th>-</th>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
    </tr>
  </thead>
  <tbody>
  <%= for task <- Tasktracker.TaskTrack.get_tasks(@current_user) do %>
  <tr>
    <td>
      <button class="time-button btn btn-secondary"
      data-task-id="<%= task.id %>"
      data-time= "" >
      Start Working
    </button>
    <td><span><%= link "Edit TimeBlock", to: time_block_path(@conn, :editblock, task), class: "btn btn-default btn-xs" %></span></td>
  </td>
  <td><%= task.title %></td>
  <td><%= task.description %></td>
  <td><%= if(task.completed) do "Completed" else "Not Completed" end %></td>

  <td class="text-right">
    <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
    <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
    <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
  </td>
</tr>
<% end %>
</tbody>
</table>
<br><br>
<h2>Manager :</h2>
<ul>
  <li><%= if @current_user.manager== nil do "No Manager" else @current_user.manager end %></li>
</ul>


<h2>Underlings: </h2>
<%= if(length(Tasktracker.Accounts.get_underlings(@current_user.email)) > 0) do %>
<ul>
<%= for user <- Tasktracker.Accounts.get_underlings(@current_user.email) do %>
<li><%= user.email %></li>
<%= end %>
<% else %>
<li><%= "No Underlings" %></li>
<%= end %>
<ul>

<% else %>
<br><br><br>
<h1><%= link "Login First", to: page_path(@conn, :index) %></h1>
<% end %>

lib/tasktracker_web/templates/task/new.html.eex
<h2>New Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/tasktracker_web/templates/task/report.html.eex
<%= if @current_user do %>
<h2>Task Report</h2>

<table class="table">
  <colgroup>
    <col class="w">
    <col class="w2">
    <col class="w2">
  </colgroup>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
    </tr>
  </thead>
  <tbody>


    <%= for task <- Tasktracker.TaskTrack.get_tasks_by_name(@current_user) do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= if(task.completed) do "Completed" else "Not Completed" end %></td>
      <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br><br>
<span><%= link "Back", to: task_path(@conn, :index) %></span>

<% else %>
<br><br><br>
<h1><%= link "Login First", to: page_path(@conn, :index) %></h1>
<% end %>

lib/tasktracker_web/templates/task/show.html.eex
<h2>Show Task</h2>

<ul>

  <li>
    <strong>User:</strong>
    <%= if @task.user do @task.user.name else "User Deleted" end %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>

  <li>
    <strong>Assigned:</strong>
    <%= if ( @task.assigned && Tasktracker.Accounts.get_user(@task.assigned)) do Tasktracker.Accounts.get_user(@task.assigned).email else "Add new Assignee" end %>
  </li>

  <li>
    <strong>Timeblocks:</strong>
    <table class="table">
      <thead>
        <tr>
          <th>Start</th>
          <th>Stop</th>
        </tr>
      </thead>
      <tbody>
        <%= for time <- Tasktracker.TaskTrack.get_blocks(@task) do %>
        <tr>
          <td><%= time.start_time %></td>
          <td><%= time.end_time %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </li>

  <li>
    <strong>Completed:</strong>
    <%= if(@task.completed) do "Completed" else "Not Completed" end %>
  </li>

</ul>
<%= if(@task.assigned == @current_user.id) do %>
<span><%= link "Back", to: task_path(@conn, :index) %></span>
<% else %>
<span><%= link "Back", to: "/tasks/report/new" %></span>
<% end %>