lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_task
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  def get_current_task(conn, _params) do
    # TODO: Move this function out of the router module.
    task_id = get_session(conn, :task_id)
    IO.inspect("#{task_id}")
    task = Tasktracker.TaskTrack.get_task(task_id || -1)
    assign(conn, :current_task, task)
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/posts", PostController
    resources "/tasks", TaskController
    get "/tasks/report/new", TaskController, :report
    post "/session", SessionController, :create
    post "/taskid", TaskidController, :create
    delete "/session", SessionController, :delete
#    get "/timeblocks1/new/:task", TimeBlockController, :new
    get "/timeblocks1/new", TimeBlockController, :new
   get "/timeblocks/:task", TimeBlockController, :editblock
  # get "/timeblocks/new/:task", TimeBlockController, :new
    post "/timeblocks/create1", TimeBlockController, :create1
    get "/timeblocks/:id/edit", TimeBlockController, :edit
    put "/timeblocks/:id", TimeBlockController, :update1
    delete "/timeblocks/:id", TimeBlockController, :delete1
  end

  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/timeblocks", TimeBlockController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker/task_track/time_block.ex
defmodule Tasktracker.TaskTrack.TimeBlock do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.TaskTrack.TimeBlock


  schema "timeblocks" do
    field :end_time, :naive_datetime
    field :start_time, :naive_datetime
    belongs_to :task, Tasktracker.TaskTrack.Task, foreign_key: :task_id

    timestamps()
  end

  @doc false
  def changeset(%TimeBlock{} = time_block, attrs) do
    time_block
    |> cast(attrs, [:start_time, :end_time, :task_id])
    |> validate_required([:start_time, :end_time, :task_id])
    |> foreign_key_constraint(:task_id)
    |> check_constraint(:end_time, [message: "should be bigger than start_time", name: "end_time_bigger" ])
  end
end

lib/tasktracker_web/controllers/time_block_controller.ex
defmodule TasktrackerWeb.TimeBlockController do
  use TasktrackerWeb, :controller

  alias Tasktracker.TaskTrack
  alias Tasktracker.TaskTrack.TimeBlock

  action_fallback TasktrackerWeb.FallbackController

  def index(conn, _params) do
    timeblocks = TaskTrack.list_timeblocks()
    render(conn, "index.json", timeblocks: timeblocks)
  end

  def create(conn, %{"time_block" => time_block_params}) do
  IO.inspect("control")
    with {:ok, %TimeBlock{} = time_block} <- TaskTrack.create_time_block(time_block_params) do
      conn
      |> put_status(:created)
      |> put_resp_header("location", time_block_path(conn, :show, time_block))
      |> render("show.json", time_block: time_block)
    end
  end

  def show(conn, %{"id" => id}) do
    time_block = TaskTrack.get_time_block!(id)

    render(conn, "show.json", time_block: time_block)
  end

  def update(conn, %{"id" => id, "time_block" => time_block_params}) do
    time_block = TaskTrack.get_time_block!(id)

    with {:ok, %TimeBlock{} = time_block} <- TaskTrack.update_time_block(time_block, time_block_params) do
      render(conn, "show.json", time_block: time_block)
    end
  end

  def delete(conn, %{"id" => id}) do
    time_block = TaskTrack.get_time_block!(id)
    with {:ok, %TimeBlock{}} <- TaskTrack.delete_time_block(time_block) do
      send_resp(conn, :no_content, "")
    end
  end

  def new(conn,  _params) do
    changeset = TaskTrack.change_time_block(%TimeBlock{})

    render(conn, "new.html", changeset: changeset)
  end

  def editblock(conn,  %{"task" => task}) do
    task
    |> IO.inspect
   render(conn, "index.html", task: task)
  end

  def create1(conn, %{"time_block" => time_block_params}) do
    case TaskTrack.create_time_block(time_block_params) do
      {:ok, timeblock} ->
        conn
        |> put_flash(:info, "Time Block created successfully.")
        |> redirect(to: task_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    time = TaskTrack.get_time_block!(id)
    changeset = TaskTrack.change_time_block(time)
    render(conn, "edit.html", time: time, changeset: changeset)
  end

  def update1(conn, %{"id" => id, "time_block" => time_params}) do
    time = TaskTrack.get_time_block!(id)

    case TaskTrack.update_time_block(time, time_params) do
      {:ok, time} ->
        conn
        |> put_flash(:info, "Time Block updated successfully.")
        |> redirect(to: time_block_path(conn, :editblock, time.task_id))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", time: time, changeset: changeset)
    end
  end

  def delete1(conn, %{"id" => id}) do
    time = TaskTrack.get_time_block!(id)
    task= time.task_id
    {:ok, _time} = TaskTrack.delete_time_block(time)

    conn
    |> put_flash(:info, "Time Block deleted successfully.")
    |> redirect(to: time_block_path(conn, :editblock, task))
  end


end

lib/tasktracker_web/views/time_block_view.ex
defmodule TasktrackerWeb.TimeBlockView do
  use TasktrackerWeb, :view
  alias TasktrackerWeb.TimeBlockView

  def render("index.json", %{timeblocks: timeblocks}) do
    %{data: render_many(timeblocks, TimeBlockView, "time_block.json")}
  end

  def render("show.json", %{time_block: time_block}) do
    %{data: render_one(time_block, TimeBlockView, "time_block.json")}
  end

  def render("time_block.json", %{time_block: time_block}) do
    %{id: time_block.id,
      start_time: time_block.start_time,
      end_time: time_block.end_time}
  end
end

lib/tasktracker_web/templates/time_block/edit.html.eex
<h2>Edit TimeBlock</h2>

<%= render "form.html", Map.put(assigns, :action, time_block_path(@conn, :update1, @time)) %>

<span><%= link "Back", to: time_block_path(@conn, :editblock, @current_task) %></span>

lib/tasktracker_web/templates/time_block/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= hidden_input f, :task_id, value: @current_task.id,  class: "form-control" %>
    <%= error_tag f, :task_id %>
  </div>

  <div class="form-group">
    <%= label f, :start_time, class: "control-label" %>
    <%= textarea f, :start_time, type: "datetime", placeholder: "YYYY-MM-DD HH:MM:SS", class: "form-control" %>
    <%= error_tag f, :start_time %>
  </div>

  <div class="form-group">
    <%= label f, :end_time, class: "control-label" %>
    <%= textarea f, :end_time, type: "datetime", placeholder: "YYYY-MM-DD HH:MM:SS", class: "form-control" %>
    <%= error_tag f, :end_time %>
  </div>


  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/time_block/index.html.eex
<%= if @current_user do %>
<h2> Time Blocks <%= @task %> </h2>
<br>
<%= form_for @conn, (taskid_path(@conn, :create)), fn f -> %>
<div class="form-group">
  <%= hidden_input f, :task_id, value: @task,  class: "form-control" %>
</div>
<!-- passwords come later -->
<div class="form-group">
  <button class="btn btn-primary">New Block</button>
  <% end %>
  <br><br>

  <table class="table">
    <thead>
      <tr>
        <th>Start</th>
        <th>Stop</th>
        <th>-</th>
      </tr>
    </thead>
    <tbody>
      <%= for time <- Tasktracker.TaskTrack.get_blocks_by_id(@task) do %>
      <tr>
        <td><%= time.start_time %></td>
        <td><%= time.end_time %></td>
        <td class="text-right">
          <span><%= link "Edit", to: time_block_path(@conn, :edit, time), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Delete", to: time_block_path(@conn, :delete1, time), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <span><%= link "Back",  class: "btn btn-primary", to: task_path( @conn, :index) %></span>
  <% end %>

lib/tasktracker_web/templates/time_block/index1.html.eex
<%= if @current_user do %>
<h2> Time Blocks </h2>
<br>
<%= form_tag("/taskid", method: :post) do %>
  <div class="form-group">
    <input type="hidden" name="task_id" value= @task.id >
  </div>
  <!-- passwords come later -->
  <br>
  <div class="form-group">
    <button class="btn btn-primary">Add TimeBlock</button>
    <% end %>
<span><%= link "Back",  class: "btn btn-primary", to: task_path( @conn, :index) %></span>
<% end %>

lib/tasktracker_web/templates/time_block/new.html.eex
<h2>New TimeBlock</h2>

<%= render "form.html", Map.put(assigns, :action, time_block_path(@conn, :create1)) %>


<span><%= link "Back", to: time_block_path(@conn, :editblock, @current_task.id) %></span>